# Generated by Django 4.1.3 on 2023-02-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0012_alter_house_building_type_alter_house_furniture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='house',
            name='image10',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='house',
            name='image11',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='house',
            name='image12',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='house',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='house',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='house',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='house',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='house',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='house',
            name='image7',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='house',
            name='image8',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='house',
            name='image9',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
